### ISSUE TITLE
Image does Not Convert

### ISSUE THREAD

**Issue by jennathull** [JohnnyWestlake/ImageConverterUWP#8]
I have downloaded and installed the Microsoft Image Converter. I am able to add file (.cr2), I have selected the output folder on my PC, Output format (.jpeg and .png) and accept the remaining defaulted settings. When I click convert the pane does show that the file is converting, but never finished. When I go check the output folder the file does appear but it is corrupt. What am I doing wrong?

**Comment by JohnnyWestlake** [comment]
Hi @jennathull  any chance you could attach one of the .cr2 files here so I can attempt to reproduce the issue and see what's going on?  (Can also provide an email address if you need it)
